- sudo:

  - link:
      /etc/apt/sources.list.d/ubuntu-fallback.list: etc/apt/sources.list.d/ubuntu-fallback.list

  - shell:
    - update-alternatives --install /usr/bin/python python /usr/bin/python2 1
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 2
    - update-alternatives --set python /usr/bin/python3
    - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

  - aptget:
      git:
      arandr:
      tig:
      git-svn:
      net-tools:
      gnome-screensaver:
      evolution:
      evolution-ews:
      tree:
      flex:
      bison:
      lzop:
      libncurses-dev:
      xmlstarlet:
      vim-gtk:
      u-boot-tools:
      python3-dev:
      python3-pip:
      autorandr:
      libow-dev:
      libsnappy-dev:
      python3:
      python3-virtualenv:
      python3-setuptools:
      virtualenv:
      feh:
      ripgrep:
      fzf:
      fd-find:
      zsh:
      p7zip:
      xclip:
      keepassxc:
      python3-ply:
      python3-git:
      libsqlite3-dev:
      nodejs:
      npm:
      python3-venv:
      nerd-font-iosevka:
      shellcheck:
      lxpolkit:

      # regolith packages
      regolith-desktop-mobile:
        ppa_source: ppa:regolith-linux/release
      regolith-look-ayu-dark:
      i3xrocks-nm-vpn:
      i3xrocks-memory:

      neovim:
        ppa_source: ppa:neovim-ppa/stable

      # wago
      wago-trace32:
      wago-devenv-2020.04:
