- sudo:

  - shell:
    - update-alternatives --install /usr/bin/python python /usr/bin/python2 1
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 2
    - update-alternatives --set python /usr/bin/python3

  - aptget:
      arandr:
      tig:
      git-svn:
      net-tools:
      gnome-screensaver:
      regolith-desktop-mobile:
        ppa_source: ppa:regolith-linux/release
      regolith-look-ayu-dark:
      i3xrocks-nm-vpn:
