- sudo:

  - shell:
    - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

  - aptget:
      tig:
      git:
      git-svn:
      net-tools:
      tree:
      flex:
      bison:
      lzop:
      libncurses-dev:
      xmlstarlet:
      vim-gtk:
      u-boot-tools:
      python3-dev:
      python3-pip:
      python3-virtualenv:
      python3-setuptools:
      python3-venv:
      python3-ply:
      python3-git:
      libow-dev:
      libsnappy-dev:
      virtualenv:
      ripgrep:
      fzf:
      fd-find:
      p7zip:
      xclip:
      keepassxc:
        ppa_source: ppa:phoerious/keepassxc
      libsqlite3-dev:
      nodejs:
      shellcheck:
      lxpolkit:
      ssh-askpass:
      parallel:
      gnome-tweaks:
      gnome-shell-extensions-gpaste:
