- sudo:
  - aptget:
      bison:
      curl:
      colordiff:
      fd-find:
      flex:
      git:
      gnome-shell-extension-gpaste:
      gnome-tweaks:
      gnupg:
      google-chrome-stable:
      htop:
      jq:
      libncurses-dev:
      libow-dev:
      libsnappy-dev:
      libsqlite3-dev:
      libssl-dev:
      lzop:
      net-tools:
      p7zip:
      python3-dev:
      python3-git:
      python3-pip:
      python3-ply:
      python3-setuptools:
      python3-venv:
      python3-virtualenv:
      ripgrep:
      shellcheck:
      tig:
      tree:
      u-boot-tools:
      virtualenv:
      pipx:

  - snap:
      sleek:

- shell:
  - pipx install keep
