- sudo:

  - link:
      /etc/apt/sources.list.d/ubuntu-fallback.list: etc/apt/sources.list.d/ubuntu-fallback.list

  - shell:
    - update-alternatives --install /usr/bin/python python /usr/bin/python2 1
    - update-alternatives --install /usr/bin/python python /usr/bin/python3 2
    - update-alternatives --set python /usr/bin/python3

  - aptget:
      arandr:
      tig:
      git-svn:
      net-tools:
      gnome-screensaver:
      evolution:
      evolution-ews:
      tree:
      flex:
      bison:
      lzop:
      libncurses-dev:
      xmlstarlet:
      vim-gtk:
      u-boot-tools:
      python3-dev:
      python3-pip:
      autorandr:

      # regolith packages
      regolith-desktop-mobile:
        ppa_source: ppa:regolith-linux/release
      regolith-look-ayu-dark:
      i3xrocks-nm-vpn:
      i3xrocks-memory:

      # wago
      wago-trace32:
      wago-devenv-2020.04:
