- sudo:

  - shell:
    # add google key for google-chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list

  - aptget:
      bison:
      ca-certificates:
      ccache:
      curl:
      direnv:
      fd-find:
      flex:
      fzf:
      git:
      gnome-shell-extensions-gpaste:
      gnome-tweaks:
      gnupg:
      google-chrome-stable:
      htop:
      jq:
      libncurses-dev:
      libow-dev:
      libsnappy-dev:
      libsqlite3-dev:
      lzop:
      net-tools:
      p7zip:
      parallel:
      python3-dev:
      python3-git:
      python3-pip:
      python3-ply:
      python3-setuptools:
      python3-venv:
      python3-virtualenv:
      ripgrep:
      shellcheck:
      ssh-askpass:
      tig:
      tree:
      u-boot-tools:
      vim-gtk:
      virtualenv:
      xclip:
      xmlstarlet:

  - shell:
    # install routine for nodejs, see https://deb.nodesource.com/
    - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
  - aptget:
      nodejs:

  - aptget:
      gnucash:
  - shell:
    # change gnucash language to german
    - sed -i 's/^Exec=\(gnucash.*\)/Exec=env LANG=de_DE.UTF-8 LANGUAGE=de_DE.UTF-8 \1/' /usr/share/applications/gnucash.desktop

  - snap:
      # bitwarden cli
      bw:

- shell:
  - pip3 install keep
