- sudo:
  - aptget:
      vim:
      py3status:
      blueman:
      tig:
      xfce4-power-manager:
      xfce4-notifyd:
      xfce4-clipman:
      xfce4-taskmanager:
      xfce4-settings:
      xfce4-terminal:
      xfce4-appfinder:
      xfce4-screenshooter:
      i3-gaps-wm:
        ppa_source: ppa:kgilmer/speed-ricer
