- sudo:
  - aptget:
      direnv:

- link:
    ~/workspace/git/u-boot/.envrc: workspace/git/u-boot/envrc
    ~/workspace/git/barebox/.envrc: workspace/git/barebox/envrc
    ~/workspace/git/linux/.envrc: workspace/git/linux/envrc
    ~/workspace/git/labgrid.basesoftware/.envrc: workspace/git/labgrid.basesoftware/envrc

- shell:
  - cd ~/workspace/git/u-boot/ && direnv allow
  - cd ~/workspace/git/barebox/ && direnv allow
  - cd ~/workspace/git/linux/ && direnv allow
  - cd ~/workspace/git/labgrid.basesoftware/ && direnv allow
