- create:
  - ~/workspace/git/

- shell:
  - GIT_PATH="${HOME}/workspace/git/ubuntu-gdm-set-background" && test -d ${GIT_PATH} || git clone https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background.git ${GIT_PATH}

- sudo:
  - shell:
    - 
      command: cd /home/wago.local/u015645/workspace/git/ubuntu-gdm-set-background && bash ubuntu-gdm-set-background --image /usr/share/backgrounds/matt-mcnulty-nyc-2nd-ave.jpg
      stdin: true
      stdout: true
      stderr: true
