- sudo:
  - aptget:
      gdm-settings:
      libglib2.0-dev-bin:

  - shell:
    # Currently i found no possibility t configure gdm settings programmetically.
    # So at least install neccesarry applications to do this manually.
    - 
      command: echo "Please open gdm-settings on your Desktop and change GDM settings"
      stdout: true
