- sudo:
  - aptget:
      dconf-cli:
      uuid-runtime:

- create:
  - ~/workspace/git/

- shell:
  - test -d ~/workspace/git/gogh || git clone https://github.com/Gogh-Co/Gogh.git ~/workspace/git/gogh
  - cd ~/workspace/git/gogh/ && TERMINAL=gnome-terminal ./apply-colors.sh themes/Ayu\ Dark.yml
