- sudo:
    - aptget:
        dconf-cli:
        uuid-runtime:

- shell:
    - command: $(git rev-parse --show-toplevel)/meta/scripts/gnome-terminal.sh "Ayu Dark"
      stdout: true
      stderr: true
