- sudo:
  - create:
    - /opt/homeserver
    - /opt/homeserver/pihole/etc-pihole
    - /opt/homeserver/pihole/etc-dnsmasq.d

  - link:
      /opt/homeserver/docker-compose.yaml: opt/homeserver/docker-compose.yaml
      /opt/homeserver/traefik: opt/homeserver/traefik
      /opt/homeserver/pihole/etc-dnsmasq.d/03-custom-dns.conf: opt/homeserver/pihole/etc-dnsmasq.d/03-custom-dns.conf
