- sudo:
    - aptget:
        build-essential:
        cargo:
        curl:
        fd-find:
        git:
        luarocks:
        nodejs:
        npm:
        python3-pynvim:
        ripgrep:
        xclip:

    - shell:
        - luarocks install --lua-version 5.1 tiktoken_core
        - npm install -g neovim

# We need newer versions of some packages as our current
# Ubuntu version serves. Install them via an alternative
# community package manager.
- shell:
    - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" brew install fzf lazygit gh lynx
    - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" brew install --force --cask font-iosevka-nerd-font

    - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        asdf plugin add neovim https://github.com/richin13/asdf-neovim &&
        asdf install neovim nightly &&
        asdf set -u neovim nightly

- shell:
    - _CONF_DIR=~/.config/nvim;
      if [ ! -d ${_CONF_DIR} ] || [ -z "$ls -A ${CONF_DIR}" ]; then git clone https://github.com/LazyVim/starter ~/.config/nvim/; fi

- link:
    ~/.local/bin/vim: $HOME/.asdf/installs/neovim/nightly/bin/nvim
    ~/.config/nvim/lua/plugins/colorscheme.lua: config/nvim/lua/plugins/colorscheme.lua
    ~/.config/nvim/lua/plugins/my-mason.lua: config/nvim/lua/plugins/mason.lua
