- sudo:
    - shell:
        - update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
        - update-alternatives --config vi
        - update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
        - update-alternatives --config vim
        - update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
        - update-alternatives --config editor

- shell:
    - pip3 install --user neovim

- link:
    ~/.config/nvim/init.lua: config/nvim/init.lua
    ~/.config/nvim/lua: config/nvim/lua
    ~/.config/nvim/stylua.toml: config/nvim/stylua.toml
