- sudo:
    - aptget:
        neovim:
          ppa_source: ppa:neovim-ppa/unstable

    - shell:
        - update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
        - update-alternatives --config vi
        - update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
        - update-alternatives --config vim
        - update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
        - update-alternatives --config editor

- create:
    - ~/.local/share/fonts

- shell:
    - pip3 install --user neovim

    # install nerd fonts for special glyphs
    - _FONT=Iosevka.tar.xz; cd ~/.local/share/fonts && curl -OL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/${_FONT} && tar xf ${_FONT} && fc-cache && rm ${_FONT}

- link:
    ~/.config/nvim/init.lua: config/nvim/init.lua
    ~/.config/nvim/lua: config/nvim/lua
    ~/.config/nvim/stylua.toml: config/nvim/stylua.toml
