- sudo:
  - shell:
    - wget -nc -q https://github.com/neovim/neovim/releases/download/v0.5.0/nvim.appimage -O /usr/local/bin/nvim && chmod ugo+x /usr/local/bin/nvim; exit 0
    - update-alternatives --install /usr/bin/vi vi /usr/local/bin/nvim 60
    - update-alternatives --config vi
    - update-alternatives --install /usr/bin/vim vim /usr/local/bin/nvim 60
    - update-alternatives --config vim
    - update-alternatives --install /usr/bin/editor editor /usr/local/bin/nvim 60
    - update-alternatives --config editor
