- sudo:
    - aptget:
        neovim:
          ppa_source: ppa:neovim-ppa/unstable

    - shell:
        - update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
        - update-alternatives --config vi
        - update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
        - update-alternatives --config vim
        - update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
        - update-alternatives --config editor

- create:
    - ~/.local/share/fonts

- shell:
    - pip3 install --user neovim

    # install nerd fonts for special glyphs
    - cd ~/.local/share/fonts && curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf && curl -fLo "Iosevka Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/Iosevka/Regular/complete/Iosevka%20Nerd%20Font%20Complete.ttf && fc-cache

- link:
    ~/.config/nvim/init.lua: config/nvim/init.lua
    ~/.config/nvim/lua: config/nvim/lua
    ~/.config/nvim/stylua.toml: config/nvim/stylua.toml
