- link:
    ~/.config/regolith/i3: config/regolith/i3
    ~/.config/regolith/i3xrocks: config/regolith/i3xrocks
    ~/.config/regolith/Xresources: config/regolith/Xresources
    ~/.Xresources-regolith: config/regolith/Xresources-regolith
    ~/.config/wallpaper: config/walls/wallpaper
