#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"

DOTBOT_DIR=$META_DIR/"dotbot.git"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGIN_DIR=$META_DIR/"plugins"

cd "${BASE_DIR}"
# git submodule update --init --recursive --remote

for config in "${@}"; do
	configFile="$(mktemp)" ; echo -e "$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")" > "$configFile"
	pluginDir="$(mktemp -d)"; for plugin in $(ls "$BASE_DIR/$PLUGIN_DIR"); do cp $BASE_DIR/$PLUGIN_DIR/$plugin/*.py "$pluginDir"; done
	"${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "$configFile" --plugin-dir "$pluginDir"; rm -f "$configFile"
done
