version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.6
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/homeserver/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /opt/homeserver/traefik/acme.json:/acme.json
      - /opt/homeserver/traefik/config.yml:/config.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_route.rule=Host(`traefik.local`)
      - traefik.http.routers.traefik_route.service=traefik_service
      - traefik.http.services.traefik_service.loadbalancer.server.port=8080

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=Europe/Berlin
      - FTLCONF_REPLY_ADDR4=192.168.178.107
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
       - /opt/homeserver/pihole/etc-pihole:/etc/pihole/
       - /opt/homeserver/pihole/etc-dnsmasq.d:/etc/dnsmasq.d/
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole_route.rule=Host(`pihole.local`)
      - traefik.http.routers.pihole_route.service=pihole_service
      - traefik.http.services.pihole_service.loadbalancer.server.port=80

  whoami1:
    image: containous/whoami
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami1_route.rule=Host(`whoami1.local`)
      - traefik.http.routers.whoami1_route.service=whoami1_service
      - traefik.http.services.whoami1_service.loadbalancer.server.port=80

  whoami2:
    container_name: "whoami2"
    image: containous/whoami
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami2_route.rule=Host(`whoami2.local`)
      - traefik.http.routers.whoami2_route.service=whoami2_service
      - traefik.http.services.whoami2_service.loadbalancer.server.port=80

networks:
  traefik:
