name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  install-script:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run install-script tests
        run: ./meta/scripts/install-test

  ubuntu-generic-profile:
    runs-on: ubuntu-24.04
    needs: install-script
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restart snapd
        run: sudo systemctl restart snapd

      - name: Set up environment
        run: |
          sudo apt-get update && sudo apt-get install -y \
            dbus-x11 \
            xvfb \
            gnome-shell \
            gnome-session \
            gnome-shell-extension-ubuntu-dock \
            gnome-shell-extension-desktop-icons-ng \
            gnome-terminal \
            gnome-settings-daemon \
            gnome-control-center \
            gsettings-desktop-schemas \
            dconf-cli

          export DISPLAY=:99
          sudo service dbus start
          Xvfb :99 -screen 0 1024x768x24 &
          gnome-session &

          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          sudo mkdir -p $XDG_RUNTIME_DIR
          sudo chown $(whoami):$(whoami) $XDG_RUNTIME_DIR
          chmod 700 $XDG_RUNTIME_DIR

          # Ensure ~/.local/bin is in PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          # Wait for GNOME session to start
          sleep 10

      - name: Run ubuntu-generic-profile tests
        run: ./install --profile ubuntu-generic
