name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true  # This will initialize and update submodules

      - name: Allow sudo without password
        run: echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$USER

      - name: Test install script itself with dummy configs
        run: ./install-test

      - name: Test ubuntu-generic profile
        run: ./install --profile ubuntu-generic
