name: Install Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true  # This will initialize and update submodules

      - name: Run install-test script
        run: ./install-test
